apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
      - name: logstash
        image: docker.evermind.de/flex4apps/logstash:latest
        ports:
          - name: hicap
            containerPort: 5555
      imagePullSecrets:
        - name: docker-evermind-de
      nodeSelector:
{{ toYaml .Values.nodeSelector | indent 8 }}        
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 100%


---
kind: Service
apiVersion: v1
metadata:
  name: logstash
spec:
  selector:
    app: logstash
  ports:
    - protocol: TCP
      port: 5555
      name: hicap
